export default Object.freeze({
    GET_DATA:           "GET_DATA",
    GET_DATA_SUCCESS:   "GET_DATA_SUCCESS",
    GET_DATA_FAIL:      "GET_DATA_FAIL",
    START_FETCHING:		"START_FETCHING",
    STOP_FETCHING:		"STOP_FETCHING",
    ADD_NEW_MESSAGE:	"ADD_NEW_MESSAGE",
    EDIT_MESSAGE:	    "EDIT_MESSAGE",
    DELETE_MESSAGE:		"DELETE_MESSAGE",
    LIKE_MESSAGE:		"LIKE_MESSAGE",
});
